<?php

declare(strict_types=1);

/**
 * @var \Ams\FrontendJsOptimization\ViewModel\BundlesLoader $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getData('view_model');

$commonBundleUrl = $viewModel->getCommonBundleUrl();
$pageBundlesUrls = $viewModel->getPageBundlesUrls();
$prefetchBundlesUrls = $viewModel->getPrefetchBundlesUrls();
?>

<?php if ($commonBundleUrl): ?>
<link rel="prefetch" href="<?= $escaper->escapeUrl($commonBundleUrl) ?>"/>
<?php endif ?>

<?php foreach ($pageBundlesUrls as $pageBundleUrl): ?>
<link rel="prefetch" href="<?= $escaper->escapeUrl($pageBundleUrl) ?>"/>
<?php endforeach ?>

<?php if ($prefetchBundlesUrls): ?>
<script>
(function(root, doc) {
    let headElement = doc.querySelector('head')
    let bundleUrls = <?= json_encode($prefetchBundlesUrls) ?>
    let idleCallback = root.requestIdleCallback || root.setTimeout
    if (headElement) {
        root.addEventListener('load', function() {
            idleCallback(function() {
                bundleUrls.forEach(function(bundleUrl) {
                    let bundleLink = doc.createElement('link');
                    bundleLink.rel = 'prefetch';
                    bundleLink.as = 'script';
                    bundleLink.href = bundleUrl;
                    headElement.appendChild(bundleLink);
                });
            });
        });
    }
}(window, document))
</script>
<?php endif ?>
